### ISSUE TITLE
USER STORY: Creating Posts

### ISSUE THREAD

**Issue by DestanT** [DestanT/we-rate-music-simplified#1]
As a **moderator** I can **create "Seasons" in the form of posts** so that **users can view them**

## Acceptance Criteria:
1. Moderators can create "Season" posts
2. All users, including moderators, can view them

## Tasks:
- [x] Template displaying posts
- [x] Form for "Season" post creation
- [x] Only moderators to have access to form element
