### ISSUE TITLE
USER STORY: Adding Spotify Playlists to Season Posts

### ISSUE THREAD

**Issue by DestanT** [DestanT/we-rate-music-simplified#13]
As a **staff/admin** I can **add Spotify playlists to specific season posts** so that **other users can view a particular post and see what playlists are a part of it**

## Acceptance Criteria:
1. Once Spotify playlists are searched for, they must be addable to a season post
2. Once added, playlists are displayed below the season title and description

## Tasks:
- [x] New model for SpotifyPlaylists, include:
   - [x] id (as PK)
   - [x] external_urls
- [x] Add button in spotify_search.html template

**Comment by DestanT** [comment]
Model - complete. Will come back to the 'add' button and its functionality after this week's planned testing.
