### ISSUE TITLE
USER STORY: Updating Season Post Images

### ISSUE THREAD

**Issue by DestanT** [DestanT/we-rate-music-simplified#16]
As a **staff member** I can **update existing images on season posts** so that **I have the flexibility to change my mind about an image previously uploaded**

## Acceptance Criteria:
1. Staff members can update image on season posts
2. Edit button

## Tasks:
- [x] UpdateView to handle logic
- [x] Edit button in season_detail.html template (near the current image)
- [ ] Delete/replace previous Cloudinary entry to save storage space on Cloudinary

**Comment by DestanT** [comment]
All tasks are complete, except clearing previous Cloudinary storage. It felt less important to do this at this time.
