### ISSUE TITLE
USER STORY: User Profile Pictures

### ISSUE THREAD

**Issue by DestanT** [DestanT/we-rate-music-simplified#17]
As a **user** I can **upload a profile picture** so that **other user can see my picture in the comments section**

## Acceptance Criteria:
1. Users able to upload profile picture
2. Have a user profile settings page

## Tasks:
- [ ] User profile settings template
- [ ] Upload to Cloudinary
- [ ] UserProfile Model
- [ ] Render profile pictures of users in comment section
