### ISSUE TITLE
USER STORY: Alert/Confirmation Pop-Ups

### ISSUE THREAD

**Issue by DestanT** [DestanT/we-rate-music-simplified#18]
As a **user of the site** I get **feedback from certain actions like deleting a comment or adding a playlist** so that **I can be sure my action was processed successfully**

## Acceptance Criteria:
1. Successfully deleting a message alert
2. Successfully updating a message alert
3. Staff user successfully adding a playlist alert

## Tasks:
- [x] Bootstrap alerts in template
- [x] Django's own 'messages' - add to CommentDeleteView, CommentUpdateView and AddPlaylistView
- [x] Add custom JS to close alert messages automatically
