### ISSUE TITLE
USER STORY: Comments

### ISSUE THREAD

**Issue by DestanT** [DestanT/we-rate-music-simplified#2]
As a **user** I can **comment on posts** so that **I can engage with the post and other users**

## Acceptance Criteria:
1. Users can post comments beneath season posts
2. Comments are displayed under season posts, in the detailed season view

## Tasks:
- [x] Create comment model
- [x] Create form element
- [x] Display comments in template

**Comment by DestanT** [comment]
Commenting is restricted to authenticated users only
