### ISSUE TITLE
USER STORY: Replies

### ISSUE THREAD

**Issue by DestanT** [DestanT/we-rate-music-simplified#3]
As a **user** I can **reply to comments** so that **I can more directly engage with specific comments from other users**

## Acceptance Criteria:
1. Users can reply to comments directly
2. Replies are offset and listed below its parent comment

## Tasks:
- [x] Create a reply model
- [x] Create a "reply" button
- [x] Form element for the reply when "reply" is pressed
- [x] Display replies, offset, under parent comment
